# Generated by Django 3.1.1 on 2020-09-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20200903_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='media_choice',
            field=models.CharField(choices=[('Audio', (('vinyl', 'Vinyl'), ('cd', 'CD'))), ('Video', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('unknown', 'Unknown')], max_length=100, null=True),
        ),
    ]
