# Generated by Django 3.1.1 on 2020-09-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_student_media_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(max_length=255, null=True, upload_to=''),
        ),
    ]
