# Generated by Django 3.1.1 on 2020-09-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_student_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=''),
        ),
    ]
